#! /bin/bash

echo
echo
echo setting up your hakpak 💻 ☠️
echo
echo installing SecLists...
echo
mkdir wordlists \
        && cd wordlists \
        && wget -c https://github.com/danielmiessler/SecLists/archive/master.zip -O SecList.zip \
        && unzip SecList.zip \
        && rm -f SecList.zip
echo
echo installing ffuf...
echo
go get github.com/ffuf/ffuf
echo
echo "NOTE: Don't forget to create an alias for ffuf!!"
